### ISSUE TITLE
Estimate price of using this GitHub action

### ISSUE THREAD

**Issue by jdnichollsc** [coderabbitai/openai-pr-reviewer#309]
Hello mate, thanks for this awesome GitHub action!

I was checking the code of the prompts [here](https://github.com/coderabbitai/openai-pr-reviewer/blob/main/src/prompts.ts#L7) and I was wondering if you can confirm how many tokens are you using with this prompt, please check this [tool](https://platform.openai.com/tokenizer) to review that.

As OpenAI explains [here](https://openai.com/pricing#language-models), more tokens === more money, so I want to estimate how many tokens are we using with this awesome tool when we create a new PR <3 

Thanks for your help!

**Comment by guritfaq** [comment]
Hard to know the cost per PR as it would vary by size but Fluxninja is averaging $15 a day for a team of 20 developers.  Hope it helps.
